# Generated by Django 5.2.5 on 2025-08-24 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_member_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('ville', models.CharField(max_length=255)),
                ('departement', models.CharField(max_length=255)),
                ('descriptiongrande', models.TextField(blank=True, null=True)),
                ('descriptionpetite', models.CharField(max_length=255)),
                ('addressemaps', models.CharField(blank=True, max_length=255, null=True)),
                ('site', models.CharField(max_length=255)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('instagram', models.EmailField(blank=True, max_length=254, null=True)),
                ('facebook', models.CharField(blank=True, max_length=255, null=True)),
                ('adresseinfos', models.CharField(blank=True, max_length=255, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='store_photos/')),
                ('slug', models.SlugField(default='', unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Member',
        ),
    ]
