# Generated by Django 5.2.5 on 2025-11-17 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0012_storeimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='super_categorie',
            field=models.CharField(choices=[('alimentation', 'Alimentation'), ('restauration', 'Restauration'), ('autres', 'Autres catégories')], default='autres', max_length=50),
        ),
    ]
