# Generated by Django 5.2.5 on 2026-01-06 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0013_store_super_categorie'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='galerie_description',
            field=models.TextField(blank=True, help_text='Description facultative pour la galerie', null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='galerie_image',
            field=models.ImageField(blank=True, help_text='Image principale pour la galerie', null=True, upload_to='store_galerie/'),
        ),
        migrations.AddField(
            model_name='store',
            name='galerie_title',
            field=models.CharField(blank=True, help_text='Titre facultatif pour la galerie du commerce', max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='OpeningHour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jour', models.CharField(choices=[('lundi', 'Lundi'), ('mardi', 'Mardi'), ('mercredi', 'Mercredi'), ('jeudi', 'Jeudi'), ('vendredi', 'Vendredi'), ('samedi', 'Samedi'), ('dimanche', 'Dimanche')], max_length=10)),
                ('matin_ouverture', models.TimeField(blank=True, null=True)),
                ('matin_fermeture', models.TimeField(blank=True, null=True)),
                ('apresmidi_ouverture', models.TimeField(blank=True, null=True)),
                ('apresmidi_fermeture', models.TimeField(blank=True, null=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opening_hours', to='members.store')),
            ],
            options={
                'ordering': ['store', 'jour'],
                'unique_together': {('store', 'jour')},
            },
        ),
    ]
