# Generated by Django 5.2.5 on 2026-01-06 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0015_add_super_categorie'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='super_categorie',
            field=models.CharField(
                max_length=50,
                choices=[
                    ('alimentation', 'Alimentation'),
                    ('restauration', 'Restauration'),
                    ('autres', 'Autres catégories'),
                ],
                default='autres',
            ),
        ),
    ]

