"""
Django settings for TestYuumi project.

Generated by 'django-admin startproject' using Django 5.2.5.
"""

from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent

# -------------------------------------------------------------
# SECURITY
# -------------------------------------------------------------

SECRET_KEY = 'django-insecure-wg1qfx-5v2%o&=)(&@t%d!9p3484j(xh^@3l8d*ns4y78l^=85'
DEBUG = True
ALLOWED_HOSTS = []

# -------------------------------------------------------------
# APPLICATIONS
# -------------------------------------------------------------

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'members',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

    # Whitenoise must be after SecurityMiddleware
    'whitenoise.middleware.WhiteNoiseMiddleware',
]

ROOT_URLCONF = 'TestYuumi.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'TestYuumi.wsgi.application'

# -------------------------------------------------------------
# DATABASE
# -------------------------------------------------------------

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# -------------------------------------------------------------
# PASSWORD VALIDATION
# -------------------------------------------------------------

AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# -------------------------------------------------------------
# INTERNATIONALIZATION
# -------------------------------------------------------------

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# -------------------------------------------------------------
# STATIC FILES (CSS, JS, IMAGES)
# -------------------------------------------------------------

# URL où les statiques seront accessibles
STATIC_URL = '/static/'

# Répertoire source des fichiers statiques (à créer dans ton projet)
STATICFILES_DIRS = [
    BASE_DIR / "static",
]

# Répertoire où collectstatic copie les fichiers pour Nginx
STATIC_ROOT = BASE_DIR / "staticfiles"

# -------------------------------------------------------------
# DEFAULT PRIMARY KEY
# -------------------------------------------------------------

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
