# Generated by Django 5.2.5 on 2026-01-14 11:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductFamily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='members.productfamily')),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('ville', models.CharField(max_length=255)),
                ('departement', models.CharField(max_length=255)),
                ('categorie', models.CharField(blank=True, max_length=100, null=True)),
                ('slugcategorie', models.SlugField(blank=True, max_length=255)),
                ('super_categorie', models.CharField(choices=[('alimentation', 'Alimentation'), ('restauration', 'Restauration'), ('autres', 'Autres catégories')], default='autres', max_length=50)),
                ('descriptionpetite', models.CharField(max_length=255)),
                ('descriptiongrande', models.TextField(blank=True, null=True)),
                ('addressemaps', models.CharField(blank=True, max_length=255, null=True)),
                ('addresseitineraire', models.CharField(blank=True, max_length=255, null=True)),
                ('site', models.CharField(max_length=255)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('instagram', models.CharField(blank=True, max_length=255, null=True)),
                ('facebook', models.CharField(blank=True, max_length=255, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='store_photos/')),
                ('galerie_title', models.CharField(blank=True, help_text='Titre facultatif pour la galerie du commerce', max_length=255, null=True)),
                ('galerie_description', models.TextField(blank=True, help_text='Description facultative pour la galerie', null=True)),
                ('galerie_image', models.ImageField(blank=True, help_text='Image principale pour la galerie', null=True, upload_to='store_galerie/')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('owner', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='store', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='productfamily',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='families', to='members.store'),
        ),
        migrations.CreateModel(
            name='StoreImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='store_photos/')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='members.store')),
            ],
        ),
        migrations.CreateModel(
            name='OpeningHour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jour', models.CharField(choices=[('lundi', 'Lundi'), ('mardi', 'Mardi'), ('mercredi', 'Mercredi'), ('jeudi', 'Jeudi'), ('vendredi', 'Vendredi'), ('samedi', 'Samedi'), ('dimanche', 'Dimanche')], max_length=10)),
                ('matin_ouverture', models.TimeField(blank=True, null=True)),
                ('matin_fermeture', models.TimeField(blank=True, null=True)),
                ('apresmidi_ouverture', models.TimeField(blank=True, null=True)),
                ('apresmidi_fermeture', models.TimeField(blank=True, null=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opening_hours', to='members.store')),
            ],
            options={
                'ordering': ['store', 'jour'],
                'unique_together': {('store', 'jour')},
            },
        ),
    ]
