# Generated by Django 5.2.5 on 2026-02-07 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='super_categorie',
            field=models.CharField(choices=[('alimentation', 'Alimentation'), ('restauration', 'Restauration'), ('autres', 'Autres catégories')], default='autres', max_length=50),
        ),
    ]
