# Generated by Django 5.2.5 on 2026-02-10 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_alter_category_super_categorie'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='last_claim_request',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
