# Generated by Django 5.2.5 on 2026-02-11 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_supercategory_alter_category_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, help_text='Image affichée sur la page ville', null=True, upload_to='categories/'),
        ),
        migrations.AddField(
            model_name='supercategory',
            name='image',
            field=models.ImageField(blank=True, help_text='Image affichée pour la super catégorie', null=True, upload_to='super_categories/'),
        ),
        migrations.CreateModel(
            name='CityCategoryHighlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departement', models.CharField(max_length=100)),
                ('ville', models.CharField(max_length=100)),
                ('categories', models.ManyToManyField(blank=True, to='members.category')),
            ],
        ),
    ]
