# Generated by Django 5.2.5 on 2025-08-26 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_store_categorie_alter_store_instagram_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='slugcategorie',
            field=models.SlugField(blank=True, max_length=255),
        ),
    ]
