# Generated by Django 5.2.5 on 2026-02-11 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_category_image_supercategory_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='citycategoryhighlight',
            name='categories',
        ),
        migrations.CreateModel(
            name='CityCategoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='members.category')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='members.citycategoryhighlight')),
                ('super_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='members.supercategory')),
            ],
            options={
                'ordering': ['ordre'],
            },
        ),
    ]
