# Generated by Django 5.2.5 on 2026-03-07 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_remove_citycategoryhighlight_categories_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='horaires_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
