# Generated by Django 5.2.5 on 2025-08-27 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_productfamily_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='disponible',
        ),
        migrations.RemoveField(
            model_name='product',
            name='prix',
        ),
    ]
