# Generated by Django 5.2.5 on 2026-04-03 12:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_store_horaires_updated_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'Catégorie', 'verbose_name_plural': 'Catégories'},
        ),
        migrations.AlterModelOptions(
            name='citycategoryhighlight',
            options={'verbose_name': 'Mise en avant ville/catégorie', 'verbose_name_plural': 'Mises en avant ville/catégorie'},
        ),
        migrations.AlterModelOptions(
            name='citycategoryitem',
            options={'verbose_name': 'Catégorie mise en avant', 'verbose_name_plural': 'Catégories mises en avant'},
        ),
        migrations.AlterModelOptions(
            name='openinghour',
            options={'ordering': ['store', models.Case(models.When(jour='lundi', then=0), models.When(jour='mardi', then=1), models.When(jour='mercredi', then=2), models.When(jour='jeudi', then=3), models.When(jour='vendredi', then=4), models.When(jour='samedi', then=5), models.When(jour='dimanche', then=6), output_field=models.IntegerField())], 'verbose_name': "Horaire d'ouverture", 'verbose_name_plural': "Horaires d'ouverture"},
        ),
        migrations.AlterModelOptions(
            name='productfamily',
            options={'verbose_name': 'Famille de produits', 'verbose_name_plural': 'Familles de produits'},
        ),
        migrations.AlterModelOptions(
            name='store',
            options={'ordering': ['nom'], 'verbose_name': 'Commerce', 'verbose_name_plural': 'Commerces'},
        ),
        migrations.AlterModelOptions(
            name='supercategory',
            options={'ordering': ['name'], 'verbose_name': 'Super catégorie', 'verbose_name_plural': 'Super catégories'},
        ),
        migrations.RenameField(
            model_name='citycategoryitem',
            old_name='city',
            new_name='highlight',
        ),
        migrations.RemoveField(
            model_name='citycategoryitem',
            name='ordre',
        ),
        migrations.RemoveField(
            model_name='citycategoryitem',
            name='super_category',
        ),
        migrations.AlterField(
            model_name='citycategoryitem',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.category'),
        ),
        migrations.AlterField(
            model_name='store',
            name='owner',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='store', to=settings.AUTH_USER_MODEL),
        ),
    ]
