# Generated by Django 5.2.5 on 2026-04-11 15:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0008_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='addresseitineraire',
            field=models.CharField(blank=True, max_length=255, null=True, validators=[django.core.validators.URLValidator(schemes=['http', 'https'])]),
        ),
        migrations.AlterField(
            model_name='store',
            name='facebook',
            field=models.CharField(blank=True, max_length=255, null=True, validators=[django.core.validators.URLValidator(schemes=['http', 'https'])]),
        ),
        migrations.AlterField(
            model_name='store',
            name='instagram',
            field=models.CharField(blank=True, max_length=255, null=True, validators=[django.core.validators.URLValidator(schemes=['http', 'https'])]),
        ),
        migrations.AlterField(
            model_name='store',
            name='site',
            field=models.CharField(blank=True, max_length=255, validators=[django.core.validators.URLValidator(schemes=['http', 'https'])]),
        ),
    ]
