# Generated by Django 5.2.5 on 2026-04-17 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0009_alter_store_addresseitineraire_alter_store_facebook_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='galerie_description',
        ),
        migrations.RemoveField(
            model_name='store',
            name='galerie_title',
        ),
    ]
