# Generated by Django 5.2.5 on 2025-08-29 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0009_store_latitude_store_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='addresseitineraire',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
