# Generated by Django 5.2.5 on 2026-04-17 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0011_store_dimanche_apresmidi_fermeture_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='galerie_image',
        ),
        migrations.CreateModel(
            name='StoreGalerieImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='store_galerie/')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='galerie_images', to='members.store')),
            ],
        ),
    ]
