# Generated by Django 5.2.5 on 2026-04-20 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0012_remove_store_galerie_image_storegalerieimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='super_categorie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='members.supercategory'),
        ),
    ]
