# Generated by Django 5.2.5 on 2026-04-20 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0013_alter_category_super_categorie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='descriptionpetite',
            field=models.TextField(blank=True, null=True),
        ),
    ]
