# Generated by Django 5.2.5 on 2026-04-20 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0014_alter_store_descriptionpetite'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='ville_precise',
            field=models.CharField(default='A définir', max_length=255),
            preserve_default=False,
        ),
    ]
