# Generated by Django 5.2.5 on 2026-04-20 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0017_pageview_ip_address_pageview_store'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreStats',
            fields=[
            ],
            options={
                'verbose_name': 'Statistique',
                'verbose_name_plural': 'Statistiques',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('members.store',),
        ),
        migrations.RemoveField(
            model_name='pageview',
            name='page',
        ),
        migrations.AddField(
            model_name='pageview',
            name='session_id',
            field=models.CharField(default='unknown', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pageview',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.store'),
        ),
    ]
