# Generated by Django 5.2.5 on 2026-04-20 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0018_storestats_remove_pageview_page_pageview_session_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pageview',
            name='session_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='pageview',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pageviews', to='members.store'),
        ),
    ]
