# Generated by Django 5.2.5 on 2026-04-20 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0020_click'),
    ]

    operations = [
        migrations.AddField(
            model_name='click',
            name='type_click',
            field=models.CharField(choices=[('itineraire', 'Itinéraire'), ('site', 'Site web'), ('instagram', 'Instagram'), ('facebook', 'Facebook'), ('telephone', 'Téléphone')], default='site', max_length=20),
        ),
    ]
