# Generated by Django 5.2.5 on 2026-04-20 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0021_click_type_click'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreClickStats',
            fields=[
            ],
            options={
                'verbose_name': 'Statistique des clics',
                'verbose_name_plural': 'Statistiques des clics',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('members.store',),
        ),
    ]
