# Generated by Django 5.2.5 on 2026-04-21 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0022_storeclickstats'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon_perso',
            field=models.ImageField(blank=True, help_text="alternative à l'icône FA", null=True, upload_to='categories/'),
        ),
    ]
