# Generated by Django 5.2.5 on 2026-04-22 10:18

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0023_category_icon_perso'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=255, null=True)),
                ('ville', models.CharField(blank=True, max_length=255, null=True)),
                ('departement', models.CharField(blank=True, max_length=255, null=True)),
                ('ville_precise', models.CharField(blank=True, max_length=255, null=True)),
                ('descriptionpetite', models.TextField(blank=True, null=True)),
                ('descriptiongrande', models.TextField(blank=True, null=True)),
                ('addressemaps', models.CharField(blank=True, max_length=255, null=True)),
                ('site', models.CharField(blank=True, max_length=255, validators=[django.core.validators.URLValidator(schemes=['http', 'https'])])),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('instagram', models.CharField(blank=True, max_length=255, null=True, validators=[django.core.validators.URLValidator(schemes=['http', 'https'])])),
                ('facebook', models.CharField(blank=True, max_length=255, null=True, validators=[django.core.validators.URLValidator(schemes=['http', 'https'])])),
                ('photo', models.ImageField(blank=True, null=True, upload_to='store_photos/')),
                ('type_suggestion', models.CharField(choices=[('new.store', 'Suggestion de nouveau commerce'), ('modif.store', 'Suggestion de modification')], max_length=20)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('acceptee', 'Acceptée'), ('refusee', 'Refusée')], default='en_attente', max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lundi', models.TextField(blank=True, null=True)),
                ('mardi', models.TextField(blank=True, null=True)),
                ('mercredi', models.TextField(blank=True, null=True)),
                ('jeudi', models.TextField(blank=True, null=True)),
                ('vendredi', models.TextField(blank=True, null=True)),
                ('samedi', models.TextField(blank=True, null=True)),
                ('dimanche', models.TextField(blank=True, null=True)),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='members.store')),
            ],
            options={
                'verbose_name': 'Suggestion',
                'verbose_name_plural': 'Suggestions',
                'ordering': ['-created_at'],
            },
        ),
    ]
