# Generated by Django 5.2.5 on 2026-04-22 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0024_storesuggestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='storesuggestion',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
