# Generated by Django 5.2.5 on 2026-04-22 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0025_storesuggestion_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='storesuggestion',
            name='produits_suggeres',
            field=models.TextField(blank=True, null=True),
        ),
    ]
