# Generated by Django 5.2.5 on 2026-04-22 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0026_storesuggestion_produits_suggeres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(help_text='Image affichée sur la page ville', null=True, upload_to='categories/'),
        ),
    ]
