# Generated by Django 5.2.5 on 2026-05-02 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0028_historicalcategory_historicalproduct_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalstore',
            name='addressemaps',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='historicalstore',
            name='descriptionpetite',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='store',
            name='addressemaps',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='store',
            name='descriptionpetite',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
