# Generated by Django 5.2.5 on 2026-05-02 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0029_alter_historicalstore_addressemaps_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='historicalcategory',
            name='icon',
        ),
        migrations.AddField(
            model_name='category',
            name='categorie_singulier',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='historicalcategory',
            name='categorie_singulier',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
