# Generated by Django 5.2.5 on 2026-05-02 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0030_remove_category_icon_remove_historicalcategory_icon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalstore',
            name='photo_medium',
            field=models.TextField(blank=True, editable=False, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalstore',
            name='photo_small',
            field=models.TextField(blank=True, editable=False, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='photo_medium',
            field=models.ImageField(blank=True, editable=False, null=True, upload_to='store_photos/'),
        ),
        migrations.AddField(
            model_name='store',
            name='photo_small',
            field=models.ImageField(blank=True, editable=False, null=True, upload_to='store_photos/'),
        ),
    ]
