# Generated by Django 5.2.5 on 2026-05-07 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0031_historicalstore_photo_medium_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supercategory',
            options={'ordering': ['ordre', 'name'], 'verbose_name': 'Super catégorie', 'verbose_name_plural': 'Super catégories'},
        ),
        migrations.AddField(
            model_name='historicalsupercategory',
            name='ordre',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='supercategory',
            name='ordre',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
