# Generated by Django 5.2.5 on 2026-05-22 13:09

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0032_alter_supercategory_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategorieIntermediaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('image', models.ImageField(blank=True, help_text='Image affichée pour la catégorie intermédiaire', null=True, upload_to='categorie_intermediaire/')),
                ('super_categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories_intermediaires', to='members.supercategory')),
            ],
            options={
                'verbose_name': 'Catégorie intermédiaire',
                'verbose_name_plural': 'Catégories intermédiaires',
                'ordering': ['ordre', 'name'],
            },
        ),
        migrations.AddField(
            model_name='category',
            name='categorie_intermediaire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sous_categories', to='members.categorieintermediaire'),
        ),
        migrations.AddField(
            model_name='historicalcategory',
            name='categorie_intermediaire',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='members.categorieintermediaire'),
        ),
        migrations.CreateModel(
            name='HistoricalCategorieIntermediaire',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField()),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('image', models.TextField(blank=True, help_text='Image affichée pour la catégorie intermédiaire', max_length=100, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('super_categorie', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='members.supercategory')),
            ],
            options={
                'verbose_name': 'historical Catégorie intermédiaire',
                'verbose_name_plural': 'historical Catégories intermédiaires',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
