# Generated by Django 5.2.5 on 2026-05-22 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0033_categorieintermediaire_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorieintermediaire',
            name='categorie_singulier',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='historicalcategorieintermediaire',
            name='categorie_singulier',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
