# Generated by Django 5.2.5 on 2026-06-21 10:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0035_fcmtoken'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPremium',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text="Coupe-circuit manuel : permet de désactiver le premium sans toucher à la date d'expiration (ex: litige paiement).")),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text="Laisser vide pour un premium sans date d'expiration (ex: compte de test, accès offert manuellement).", null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='premium', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Statut Premium',
                'verbose_name_plural': 'Statuts Premium',
            },
        ),
    ]
