# Generated by Django 5.2.5 on 2026-06-25 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0037_aiusagelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiusagelog',
            name='web_search_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
