# Generated by Django 5.2.5 on 2026-06-28 15:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0039_wishlist_wishliststore_wishlist_stores_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, help_text='Note privée, visible uniquement par son auteur.', max_length=1000)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_notes', to='members.store')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Note personnelle',
                'verbose_name_plural': 'Notes personnelles',
                'unique_together': {('user', 'store')},
            },
        ),
    ]
