# Generated by Django 5.2.5 on 2026-06-29 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0040_storenote'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpremium',
            name='external_subscription_id',
            field=models.CharField(blank=True, help_text="ID de l'abonnement chez le prestataire (ex: sub_xxx chez Stripe), pour relier un webhook a cet utilisateur sans dependre d'un seul prestataire.", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userpremium',
            name='payment_provider',
            field=models.CharField(blank=True, help_text="Prestataire ayant confirmé le paiement : 'stripe', 'lemonsqueezy', 'manuel'... Vide si jamais payé (ex: premium offert directement par l'admin).", max_length=30),
        ),
    ]
