# Generated by Django 5.2.5 on 2026-06-30 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0041_userpremium_external_subscription_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpremium',
            name='billing_period',
            field=models.CharField(choices=[('monthly', 'Mensuel'), ('annual', 'Annuel')], default='monthly', help_text='Périodicité de facturation : mensuel ou annuel.', max_length=10),
        ),
        migrations.AddField(
            model_name='userpremium',
            name='tier',
            field=models.CharField(choices=[('yuumi_plus', 'Yuumi+'), ('premium', 'Yuumi Premium')], default='yuumi_plus', help_text="Niveau d'abonnement : Yuumi+ ou Yuumi Premium.", max_length=20),
        ),
        migrations.AlterField(
            model_name='userpremium',
            name='external_subscription_id',
            field=models.CharField(blank=True, help_text="ID de l'abonnement chez le prestataire (ex: sub_xxx chez Stripe).", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userpremium',
            name='payment_provider',
            field=models.CharField(blank=True, help_text="Prestataire ayant confirmé le paiement : 'stripe', 'paypal', 'manuel'...", max_length=30),
        ),
    ]
